apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # The ACME server URL
    #testserver
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: bioxvirizm@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
       # Enable the HTTP-01 challenge provider
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bioxvirizm
  namespace: default
spec:
  secretName: bioxvirizm-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: doku.bioxvirizm.online
  dnsNames:
  - doku.bioxvirizm.online
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/issuer: "letsencrypt-prod"
  name: app
spec:
  tls:
  - hosts:
    - doku.bioxvirizm.online
    secretName: bioxvirizm-tls
  rules:
  - host: doku.bioxvirizm.online
    http:
      paths:
      - pathType: Prefix  
        path: /
        backend:
          service:
            name: doku-service
            port:
              number: 80
