apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/issuer: "letsencrypt"
  name: {{ .Release.Name }}-app
spec:
  tls:
  - hosts:
    - devdoku.bioxvirizm.online
    secretName: bioxvirizm-tls
  rules:
  - host: devdoku.bioxvirizm.online
    http:
      paths:
      - pathType: Prefix  
        path: /
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 80