apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  labels:
    app: {{ .Release.Name }}
spec:
  containers:
  - name: dokuwiki
    image: {{ .Values.container.image }}
    env:
    - name: PUID
      value: "1000"
    - name: -PGID
      value: "1000"
    - name: -TZ
      value: EUROPE/Minsk
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: web
        containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /config
      name: nfs
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: {{ .Release.Name }}-pvc



