apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: csi-nfs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi