apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
spec:
  #type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
